general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = ~/Pictures/wallpapers/green-forest.jpg
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    outer_color = rgba(458588ff)
    inner_color = rgba(282828ff)
    font_color = rgba(ebdbb2ff)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}
#label time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(ebdbb2ff)
    font_size = 72
    font_family = JetBrains Mono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}
#label date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(d5c4a1ff)
    font_size = 24
    font_family = JetBrains Mono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}